server:
  port: 8080

spring:
  application:
    name: hotel-booking-api
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=DoAnHotelParkingDb;encrypt=true;trustServerCertificate=true
    username: sa
    password: 123456
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
        format_sql: true
        physical_naming_strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

app:
  jwt:
    issuer: DoAn.HotelParking
    audience: DoAn.HotelParking.Client
    secret-key: DoAn.HotelParking.Super.Secret.Key.2026
    access-token-expiration-minutes: 60
  minio:
    endpoint: http://localhost:9000
    access-key: minioadmin
    secret-key: minioadmin
    bucket-name: hotel-images
    public-base-url: http://localhost:9000
    auto-create-bucket: true
  firebase:
    credentials-path: firebase/hotelapp-63196-firebase-adminsdk-fbsvc-a126f141e7.json
    project-id: hotelapp-63196

springdoc:
  swagger-ui:
    path: /swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
